import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from './provider'
import { Toaster } from "@/components/ui/sonner";
import Footer from "./_components/footer";
const outfit = Outfit({
  variable: "--font - outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit}  antialiased`}
      >
         <NextAuthSessionProvider>
        <div className="mx-6 md:mx-16">
       <Header/>
        <Toaster />
        {children}
        <Footer/>
        </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
